TodoHonduras/CapaPresentacionTienda/Controllers/TiendaController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CapaPresentacionTienda.Controllers
{
    public class TiendaController : Controller
    {
        // GET: Tienda
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Carrito()
        {
            return View();
        }

        #region DetalleProducto
        public ActionResult DetalleProducto(int idproducto = 0)
        {
            Producto oProducto = new Producto();
            bool conversion;

            oProducto = new CN_Producto().Listar().Where(p => p.IdProducto == idproducto).FirstOrDefault();

            if (oProducto != null)
            {
                oProducto.Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oProducto.RutaImagen, oProducto.NombreImagen), out conversion);
                oProducto.Extension = Path.GetExtension(oProducto.NombreImagen);

            }

            return View(oProducto);
        }
        #endregion

        #region CATEGORIA_LISTAR
        [HttpGet]
        public JsonResult ListaCategorias()
        {
            List<Categoria> lista = new List<Categoria>();

            lista = new CN_Categoria().Listar();

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region MARCA_LISTAR
        [HttpPost]
        public JsonResult ListarMarcaporCategoria(int idcategoria)
        {
            List<Marca> lista = new List<Marca>();

            lista = new CN_Marca().ListarMarcaporCategoria(idcategoria);

            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);

        }
        #endregion

        #region LISTAR PRODUCTO
        [HttpPost]
        public JsonResult ListarProductos(int idcategoria, int idmarca)
        {
            List<Producto> lista = new List<Producto>();

            bool conversion;


            lista = new CN_Producto().Listar().Select(p => new Producto()
            {
                IdProducto = p.IdProducto,
                Nombre = p.Nombre,
                Descripcion = p.Descripcion,
                oMarca = p.oMarca,
                oCategoria = p.oCategoria,
                Precio = p.Precio,
                Stock = p.Stock,
                RutaImagen = p.RutaImagen,
                Base64 = CN_Recursos.ConvertirBase64(Path.Combine(p.RutaImagen, p.NombreImagen), out conversion),
                Extension = Path.GetExtension(p.NombreImagen),
                Activo = p.Activo
            }).Where(p =>
                p.oCategoria.IdCategoria == (idcategoria == 0 ? p.oCategoria.IdCategoria : idcategoria) &&
                p.oMarca.IdMarca == (idmarca == 0 ? p.oMarca.IdMarca : idmarca) &&
                p.Stock > 0 && p.Activo == true
            ).ToList();

            var jsonresult = Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            jsonresult.MaxJsonLength = int.MaxValue;

            return jsonresult;
        }
        #endregion

        #region CARRITO

        [HttpPost]
        public JsonResult AgregarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool existe = new CN_Carrito().ExisteCarrito(idcliente, idproducto);

            bool respuesta = false;

            string mensaje = string.Empty;

            if (existe)
            {
                mensaje = "El producto ya existe en el carrito";
            }
            else
            {
                respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, true, out mensaje);
            }

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult CantidadEnCarrito()
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            int cantidad = new CN_Carrito().CantidadEnCarrito(idcliente);
            return Json(new { cantidad = cantidad }, JsonRequestBehavior.AllowGet);
        }

        #region PRODUCTO DENTRO DEL CARRITO

        [HttpPost]
        public JsonResult ListarProductoCarrito()
        {
            // Verificar si la sesión "Cliente" está definida
            if (Session["Cliente"] == null)
            {
                return Json(new { success = false, message = "No ha iniciado sesión." }, JsonRequestBehavior.AllowGet);
            }

            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;
            
            List<Carrito> oLista = new List<Carrito>();

            bool conversion;

            oLista = new CN_Carrito().ListarProducto(idcliente).Select(oc => new Carrito()
            {
                oProducto = new Producto()
                {
                    IdProducto = oc.oProducto.IdProducto,
                    Nombre = oc.oProducto.Nombre,
                    oMarca = oc.oProducto.oMarca,
                    Precio = oc.oProducto.Precio,
                    RutaImagen = oc.oProducto.RutaImagen,
                    Base64 = CN_Recursos.ConvertirBase64(Path.Combine(oc.oProducto.RutaImagen, oc.oProducto.NombreImagen), out conversion),
                    Extension = Path.GetExtension(oc.oProducto.NombreImagen)
                },
                Cantidad = oc.Cantidad
            }).ToList();

            // Ajustar el tamaño máximo del JSON si es necesario
            var jsonResult = Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
        #endregion


        [HttpPost]
        public JsonResult OperacionCarrito(int idproducto, bool sumar)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool respuesta = false;

            string mensaje = string.Empty;

            respuesta = new CN_Carrito().OperacionCarrito(idcliente, idproducto, sumar, out mensaje);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCarrito(int idproducto)
        {
            int idcliente = ((Cliente)Session["Cliente"]).IdCliente;

            bool respuesta = false;

            string mensaje = string.Empty;

            respuesta = new CN_Carrito().EliminarCarrito(idcliente, idproducto);

            return Json(new { respuesta = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        
        #endregion

        #region Ubicación

        [HttpPost]
        public JsonResult ObtenerDepartamento()
        {
            List<Departamento> oLista = new List<Departamento>();

            oLista = new CN_Ubicacion().ObtenerDepartamento();

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerMunicipio(string IdDepartamento)
        {
            List<Municipio> oLista = new List<Municipio>();

            oLista = new CN_Ubicacion().ObtenerMunicipio(IdDepartamento);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ObtenerAldea(string IdDepartamento, string IdMunicipio)
        {
            List<Aldea> oLista = new List<Aldea>();

            oLista = new CN_Ubicacion().ObtenerAldea(IdDepartamento, IdMunicipio);

            return Json(new { lista = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

TodoHonduras/CapaPresentacionTienda/Views/Tienda/DetalleProducto.cshtml
@model CapaEntidad.Producto
@{
    ViewBag.Title = "DetalleProducto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="data:image/@Html.DisplayTextFor(m => m.Extension);base64,@Html.DisplayTextFor(m => m.Base64)" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">Marca: @Html.DisplayTextFor(m => m.oMarca.Descripcion)</div>
                <h1 class="display-5 fw-bolder">@Html.DisplayTextFor(m => m.Nombre)</h1>
                <div class="fs-5 mb-5">
                    <span>@Html.DisplayTextFor(m => m.Precio) LPS</span>
                </div>
                <p class="lead">@Html.DisplayTextFor(m => m.Descripcion)</p>
                <div class="d-flex">

                    <a href="@Url.Action("Index","Tienda")" class="btn btn-danger w-50 text-center me-3">
                        <i class="fas fa-undo-alt"></i> Volver

                    </a>

                    @if (Session["Cliente"] != null)
                    {
                        <button class="btn btn-success agregarcarrito flex-shrink-0 w-50" type="button" data-idproducto="@Html.DisplayTextFor(m => m.IdProducto)">
                            <i class="fas fa-cart-plus"></i>Agregar al Carrito
                        </button>
                    }


                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    
    <script>

        $(document).on("click", "button.agregarcarrito", function () {

            console.log($(this).data("idproducto"))

            jQuery.ajax({
                url: '@Url.Action("AgregarCarrito", "Tienda")',
                type: "POST",
                data: JSON.stringify({ idproducto: $(this).data("idproducto") }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.respuesta) {

                        MostrarCantidadCarrito();

                        @*swal({
                            title: "Agregado al carrito",
                            text: "¿Desea ir al carrito?",
                            type: "Success",
                            showCancelButton: true,
                            confirmButtonClass: "btn-primary",
                            confirmButtonText: "Si",
                            cancelButtonText: "No",
                            closeOnConfirm: true
                        }, function () {

                            window.location.href = '@Url.Action("Carrito","Tienda")'

                        })*@

                        swal("", "Agregado al carrito", "success");
                    } else {
                        swal("", data.mensaje, "warning");
                    }
                }
            });

        })

    </script>

    }

TodoHonduras/CapaPresentacionTienda/Views/Tienda/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Todo Honduras</h1>
            <p class="lead fw-normal text-white-50 mb-0">Productos 100% hondureño</p>
        </div>
    </div>
</header>
<!-- Section-->
<section">
    <div class="container-fluid px-5 my-5">

        <div class="row">

            <div class="col-sm-3">

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Categorias
                            </div>

                            <div id="contenedor_categoria" class="card-body">
                                
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="card">
                            <div class="card-header bg-dark text-white">
                                Marcas
                            </div>

                            <div id="contenedor_marca" class="card-body">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-12">
                        <div class="d-grid gap-2">
                            <button id="btnaplicarfiltro" class="btn btn-outline-dark btn-block" type="button">
                                <i class="fas fa-filter"></i> Aplicar Filtros
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-9">
                <div id="contenedor_producto" class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Fancy Product</h5>
                                    <!-- Product price-->
                                    $40.00 - $80.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">Special Item</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">$20.00</span>
                                    $18.00
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</section">

@section scripts{
    <script>

        $(document).ready(function () {
            MostrarCategorias();
            MostrarProducto(0, 0)
        })

        function MostrarCategorias() {
            jQuery.ajax({
                url: "@Url.Action("ListaCategorias", "Tienda")",
                type: "GET",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {

                    $("#contenedor_categoria").LoadingOverlay("hide");

                    $("<div>").addClass("form-check").append(

                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": "0", "id": "cx", "checked":"checked"}),
                        $("<label>").addClass("form-check-label").text("Todos").attr({ "for":"cx"})
                    ).appendTo("#contenedor_categoria")


                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("form-check").append(

                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "categoria", "value": element.IdCategoria, "id": "c" + i}),
                            $("<label>").addClass("form-check-label").text(element.Descripcion).attr({ "for": "c" + i })
                        ).appendTo("#contenedor_categoria")
                    })

                    MostrarMarca();
                },
                beforeSend: function () {
                    $("#contenedor_categoria").LoadingOverlay("show");
                }
            })
        }


        function MostrarMarca() {

            var _idcategoria = $("input[name=categoria]:checked").val()

            jQuery.ajax({
                url: "@Url.Action("ListarMarcaporCategoria", "Tienda")",
                type: "POST",
                data: JSON.stringify({ idcategoria: _idcategoria }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {

                    $("#contenedor_marca").html("");
                    $("#contenedor_marca").LoadingOverlay("hide");

                    $("<div>").addClass("form-check").append(

                        $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": "0", "id": "mx", "checked":"checked"}),
                        $("<label>").addClass("form-check-label").text("Todos").attr({ "for":"mx"})
                    ).appendTo("#contenedor_marca")


                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("form-check").append(

                            $("<input>").addClass("form-check-input").attr({ "type": "radio", "name": "marca", "value": element.IdMarca, "id": "m" + i}),
                            $("<label>").addClass("form-check-label").text(element.Descripcion).attr({ "for": "m" + i })
                        ).appendTo("#contenedor_marca")
                    })

                },
                beforeSend: function () {
                    $("#contenedor_marca").LoadingOverlay("show");
                }
            })
        }

        $(document).on("change", "input[name=categoria]", function () {
            MostrarMarca()
        })

        function MostrarProducto(_idcategoria,_idmarca) {

            jQuery.ajax({
                url: "@Url.Action("ListarProductos", "Tienda")",
                type: "POST",
                data: JSON.stringify({ idcategoria: _idcategoria, idmarca: _idmarca }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {

                    $("#contenedor_producto").html("");
                    $("#contenedor_producto").LoadingOverlay("hide");

                    $.each(response.data, function (i, element) {
                        $("<div>").addClass("col mb-5").append(

                            $("<div>").addClass("card h-100").append(
                                $("<img>").addClass("card-img-top").attr({ "src": "data:image/" + element.Extension + ";base64," + element.Base64 }),
                                $("<div>").addClass("card-body p-4").append(
                                    $("<div>").addClass("text-center").append(
                                        $("<h5>").addClass("fw-bolder").text(element.Nombre),
                                        "$ " + element.Precio.toFixed(2) + " LPS"
                                    )
                                ),

                                $("<div>").addClass("card-footer p-4 pt-0 border-top-0 bg-transparent").append(

                                    /*BOTONES*/
                                    $("<div>").addClass("d-grid gap-2").append(
                                        @if (Session["Cliente"] != null)
                                         {
                                            @:$("<button>").addClass("btn btn-success mt-auto agregarcarrito").data("idproducto", element.IdProducto).text("Agregar al Carrito"),
                                         }

                                            $("<a>").addClass("btn btn-dark mt-auto")
                                                .attr({ "href": "@Url.Action("DetalleProducto","Tienda")" + "?idproducto=" + element.IdProducto })
                                            .text("Ver detalle")
                                    )

                                )

                            )

                        ).appendTo("#contenedor_producto")
                    })

                },
                beforeSend: function () {
                    $("#contenedor_producto").LoadingOverlay("show");
                }
            })
        }

        $("#btnaplicarfiltro").click(function () {
            var _idcategoria = $("input[name=categoria]:checked").val()
            var _idmarca = $("input[name=marca]:checked").val()
            MostrarProducto(_idcategoria, _idmarca)
        })

        $(document).on("click", "button.agregarcarrito", function () {

            console.log($(this).data("idproducto"))

            jQuery.ajax({
                url: '@Url.Action("AgregarCarrito", "Tienda")',
                type: "POST",
                data: JSON.stringify({ idproducto: $(this).data("idproducto") }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.respuesta) {

                        MostrarCantidadCarrito();

                        swal({
                            title: "Agregado al carrito",   
                            text: "¿Desea ir al carrito?",
                            type: "success",
                            showCancelButton: true,
                            confirmButtonClass: "btn-primary",
                            confirmButtonText: "Si",
                            cancelButtonText: "No",
                            closeOnConfirm: true
                        }, function () {

                            window.location.href = '@Url.Action("Carrito","Tienda")'

                        })
                    } else {
                        swal("", data.mensaje, "warning");
                    }
                }
            });

        })

    </script>
    }