TodoHonduras/CapaPresentacionAdmin/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    [Authorize]
    public class MantenedorController : Controller
    {
        #region CATEGORIA
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = new CN_Categoria().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdCategoria == 0)
            {
                resultado = new CN_Categoria().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Categoria().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region MARCA

        public ActionResult Marca()
        {
            return View();
        }


        [HttpGet]
        public JsonResult ListarMarcas()
        {
            List<Marca> oLista = new List<Marca>();
            oLista = new CN_Marca().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(Marca objeto)
        {
            object resultado;
            string mensaje = string.Empty;

            if (objeto.IdMarca == 0)
            {
                resultado = new CN_Marca().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region PRODUCTO
        public ActionResult Producto()
        {
            return View();
        }

        [HttpGet]
        public JsonResult listarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = new CN_Producto().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult GuardarProducto(string objeto, HttpPostedFileBase archivoImagen)
        {
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool guardar_imagen_exito = true;

            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio;

            if (decimal.TryParse(oProducto.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-HN"), out precio))
            {
                oProducto.Precio = precio;
            }
            else
            {
                return Json(new { operacionExitosa = false, mensaje = "El formato del precio debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }

            if (oProducto.IdProducto == 0)
            {
                int idProductoGenerado = new CN_Producto().Registrar(oProducto, out mensaje);

                if (idProductoGenerado != 0)
                {
                    oProducto.IdProducto = idProductoGenerado;
                }
                else
                {
                    operacion_exitosa = false;
                }
            }
            else
            {
                operacion_exitosa = new CN_Producto().Editar(oProducto, out mensaje);
            }

            //imagen
            if (operacion_exitosa)
            {
                if (archivoImagen != null)
                {
                    string ruta_guardar = ConfigurationManager.AppSettings["ServidorFotos"];
                    string extension = Path.GetExtension(archivoImagen.FileName);
                    string nombre_imagen = string.Concat(oProducto.IdProducto.ToString(), extension);

                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(ruta_guardar, nombre_imagen));
                    }
                    catch (Exception ex)
                    {
                        string msg = ex.Message;
                        guardar_imagen_exito = false;
                    }

                    if (guardar_imagen_exito)
                    {
                        oProducto.RutaImagen = ruta_guardar;
                        oProducto.NombreImagen = nombre_imagen;

                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }
                    else
                    {
                        mensaje = "Se guardo el producto pero hubo problemas con la imagen";
                    }
                }
            }
            return Json(new { operacionExitosa = operacion_exitosa, idGenerado = oProducto.IdProducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ImagenProducto(int id)
        {
            bool conversion;
            Producto oproducto = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textoBase64 = CN_Recursos.ConvertirBase64(Path.Combine(oproducto.RutaImagen, oproducto.NombreImagen), out conversion);

            return Json(new
            {
                conversion = conversion,
                textobase64 = textoBase64,
                extension = Path.GetExtension(oproducto.NombreImagen)
            },

            JsonRequestBehavior.AllowGet

            );
        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

TodoHonduras/CapaPresentacionAdmin/Views/Mantenedor/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>

<div class="card">
    <div class="card-header">

        <i class="fas fa-table me-1"></i> Lista de Categorias
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                @*boton de crear usuario y dentro del boton un evento clic abrir alert o modal*@
                <button type="button" class="btn btn-success" onclick="AbrirModal(null)">Crear Nuevo</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width: 100%">

            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="staticBackdropLabel">Categoria</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />

                @*fila*@
                <div class="row g-2">

                    @*Columna dentro del modal para los campos*@
                    <div class="col-sm-6">
                        <label for="txtdescripcion" class="form-label">Descripción</label>
                        <input type="text" class="form-control" id="txtdescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>


                </div>

                <!--alerta mensaje-->
                <div class="row mt-3">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>

        var tabladata;
        var filaSeleccionada

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarCategorias", "Mantenedor")',
                type: "GET",
                dataType: "json",
            },
            "columns": [
                {"data":"Descripcion"},
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Si</span>'
                        } else {
                            return '<span class="badge bg-danger">No</span>'
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2  btn-eliminar"><i class="fas fa-trash me-1"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language" : {
                "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"
            }
        });

        /*funcion para abrirModal y dentro el id del modal*/

        function AbrirModal(json) {

            $("#txtid").val(0);
            $("#txtdescripcion").val("");
            $("#cboactivo").val(1);


            $("#mensajeError").hide();


            if (json != null) {

                $("#txtid").val(json.IdCategoria);
                $("#txtdescripcion").val(json.Descripcion);
                $("#cboactivo").val(json.Activo == true ? 1 : 0);

            }

            $("#FormModal").modal("show");
        }


        /*cada vez que den clic al boton de lapiz dentro de nuestra tabla actualice los datos*/

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            AbrirModal(data)

        })

        /*cada vez que den clic al boton de basura dentro de nuestra tabla elimine los datos*/

        $("#tabla tbody").on("click", '.btn-eliminar', function () {

           var datoseleccionado = $(this).closest("tr");

            var data = tabladata.row(datoseleccionado).data();

            swal({
                title: "¿Estás seguro?",
                text: "¿Desea eliminar la categoria?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
            function () {

                    jQuery.ajax({
                        url: '@Url.Action("EliminarCategoria", "Mantenedor")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdCategoria }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {

                                tabladata.row(datoseleccionado).remove().draw();
                            } else {

                                swal("No se pudo eliminar", data.mensaje, "error")

                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    });
            });

            console.log(data);

        })

        function Guardar() {

            var Categoria = {

                IdCategoria: $("#txtid").val(),
                Activo: $("#cboactivo").val() == 1 ? true: false,
                Descripcion: $("#txtdescripcion").val()
            }


            jQuery.ajax({
                url: '@Url.Action("GuardarCategoria", "Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: Categoria }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide")

                    //NUEVO
                    if (Categoria.IdCategoria == 0) {

                        if (data.resultado != 0) {
                            swal("Categoria Guardada", "Click en el Boton", "success")
                            Categoria.IdCategoria = data.resultado;
                            tabladata.row.add(Categoria).draw(false);
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                    //EDITAR
                    else
                    {
                        if (data.resultado)
                        {
                            tabladata.row(filaSeleccionada).data(Categoria).draw(false);
                            swal("Categoria Editada", "Click en el Boton", "success")
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        }
                        else
                        {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {

                    $(".modal-body").LoadingOverlay("hide")
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageRizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }
            });
        }
    </script>

}

TodoHonduras/CapaPresentacionAdmin/Views/Mantenedor/Marca.cshtml
@{
    ViewBag.Title = "Marca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Marcas</li>
</ol>

<div class="card">
    <div class="card-header">

        <i class="fas fa-bookmark me-1"></i> Lista de Marcas
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                @*boton de crear usuario y dentro del boton un evento clic abrir alert o modal*@
                <button type="button" class="btn btn-success" onclick="AbrirModal(null)">Crear Nuevo</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width: 100%">

            <thead>
                <tr>
                    <th>Descripción</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="staticBackdropLabel">Marca</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <input id="txtid" type="hidden" value="0" />

                @*fila*@
                <div class="row g-2">

                    @*Columna dentro del modal para los campos*@
                    <div class="col-sm-6">
                        <label for="txtdescripcion" class="form-label">Descripción</label>
                        <input type="text" class="form-control" id="txtdescripcion" autocomplete="off">
                    </div>

                    <div class="col-sm-6">
                        <label for="cboactivo" class="form-label">Activo</label>
                        <select id="cboactivo" class="form-select">
                            <option value="1">Si</option>
                            <option value="0">No</option>
                        </select>
                    </div>


                </div>

                <!--alerta mensaje-->
                <div class="row mt-3">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                          
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>

        var tabladata;
        var filaSeleccionada

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMarcas", "Mantenedor")',
                type: "GET",
                dataType: "json",
            },
            "columns": [
                {"data":"Descripcion"},
                {
                    "data": "Activo", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Si</span>'
                        } else {
                            return '<span class="badge bg-danger">No</span>'
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen me-1"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2  btn-eliminar"><i class="fas fa-trash me-1"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language" : {
                "url": "https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"
            }
        });

        /*funcion para abrirModal y dentro el id del modal*/

        function AbrirModal(json) {

            $("#txtid").val(0);
            $("#txtdescripcion").val("");
            $("#cboactivo").val(1);


            $("#mensajeError").hide();


            if (json != null) {

                $("#txtid").val(json.IdMarca);
                $("#txtdescripcion").val(json.Descripcion);
                $("#cboactivo").val(json.Activo == true ? 1 : 0);

            }

            $("#FormModal").modal("show");
        }


        /*cada vez que den clic al boton de lapiz dentro de nuestra tabla actualice los datos*/

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            AbrirModal(data)

        })

        /*cada vez que den clic al boton de basura dentro de nuestra tabla elimine los datos*/

        $("#tabla tbody").on("click", '.btn-eliminar', function () {

           var datoseleccionado = $(this).closest("tr");

            var data = tabladata.row(datoseleccionado).data();

            swal({
                title: "¿Estás seguro?",
                text: "¿Desea eliminar la marca?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
            function () {

                    jQuery.ajax({
                        url: '@Url.Action("EliminarMarca", "Mantenedor")',
                        type: "POST",
                        data: JSON.stringify({ id: data.IdMarca }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {

                                tabladata.row(datoseleccionado).remove().draw();
                            } else {

                                swal("No se pudo eliminar", data.mensaje, "error")

                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    });
            });

            console.log(data);

        })

        function Guardar() {

            var Marca = {

                IdMarca: $("#txtid").val(),
                Activo: $("#cboactivo").val() == 1 ? true: false,
                Descripcion: $("#txtdescripcion").val()
            }


            jQuery.ajax({
                url: '@Url.Action("GuardarMarca", "Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: Marca }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide")

                    //NUEVO
                    if (Marca.IdMarca == 0) {

                        if (data.resultado != 0) {
                            swal("Marca Guardada", "Click en el Boton", "success")
                            Marca.IdMarca = data.resultado;
                            tabladata.row.add(Marca).draw(false);
                            $("#FormModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }

                    //EDITAR
                    else
                    {
                        if (data.resultado)
                        {
                            tabladata.row(filaSeleccionada).data(Marca).draw(false);
                            swal("Marca Editada", "Click en el Boton", "success")
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        }
                        else
                        {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {

                    $(".modal-body").LoadingOverlay("hide")
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageRizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }
            });
        }
    </script>

}